# Generated by Django 5.0.3 on 2024-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kwHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=10)),
                ('datetime', models.IntegerField()),
                ('rank', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='kwRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=10)),
                ('rank', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='newsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('reporter', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=10)),
                ('datetime', models.CharField(max_length=10)),
                ('summary', models.TextField(default=' ')),
                ('url', models.URLField(null=True)),
                ('keywords', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
