# Generated by Django 4.2.7 on 2024-03-27 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0002_newslistdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsListData",
        ),
    ]
