# Generated by Django 5.0.3 on 2024-03-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
        ('newslist', '0002_remove_newslistdata_pub_date_newslistdata_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.newsdata')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsListData',
        ),
    ]
